### ISSUE TITLE
As a user, I want to be able to like a user's post

### ISSUE THREAD

**Issue by JackieDan** [Polaroid-Soen-341/SOEN341#3]
As a user, I want to like posts & comments created by other users or my own.
- When I select a post I have the option to like it
- Posts display how many likes they have accumulated in total
- When I select a comment I should have the option to like it
- I can see how many times a comment has been liked

Tasks
- [ ] Add like field to post models and comment models
- [ ] Add like button to each post and comment in the frontend
- [ ] Create frontend function that sends a request to the backend when like button is clicked
- [ ] Store the number of likes for each post and comment in the backend

Priority: Low needed for sprint 4

**Comment by NathanFortier** [comment]
This issue was cut from the project
