### ISSUE TITLE
As a user, I want to follow other users.

### ISSUE THREAD

**Issue by Hamna-Akh** [Polaroid-Soen-341/SOEN341#4]
As a user, I want to follow other users. I also want other to be able to follow me.

- I am be able to unfollow other users.
- I am able to follow other users
- I can see who follows me
- I can see who someone else follows
- Others can see who I follow

Tasks
- [x]  Create follow button on profile and on posts. #
- [x]  Create function that sends http request for following a user
- [x]  Implement the fields followers and following as part of the User model #40 
- [x]  Display followers and following for a specific user
- [x]  Implement unfollow feature
- [x]  Allow access to other user profile
- [x]  Have posts of users you follow appear in the feed.

Story Points: 7

**Comment by JackieDan** [comment]
Follow feature was successfully implemented. Closing Issue.

**Comment by Hamna-Akh** [comment]
<img width="646" alt="AT#6" src="https://user-images.githubusercontent.com/77466360/114938051-a29e1f80-9e0c-11eb-90c3-ac945485e793.png">

**Comment by JackieDan** [comment]
Everything related to following and unfollowing users has been implemented and tested. Closing issue #4
