### ISSUE TITLE
As a user I would like to get a feed 

### ISSUE THREAD

**Issue by NathanFortier** [Polaroid-Soen-341/SOEN341#49]
As a user, I would like to see the newest content added by people I follow.

- There is a feed page accessible once I log in
- The feed will feature posts from only people I follow
- The feed will change dynamically based on what is has been posted most recently
- I can access posts in the feed to be able to comment or like
- My posts should not be in my feed.

Tasks
- [x] In the frontend, create a feed component that will be replicated for each post
- [x] Retrieve posts made by followed users from the database
- [x] Update the feed when a followed person posts something new

Priority
Low needed to be complete for Sprint 4

**Comment by Hamna-Akh** [comment]
<img width="698" alt="AT#5" src="https://user-images.githubusercontent.com/77466360/114640922-11f60100-9c9f-11eb-97b5-030107ed5392.png">

**Comment by JackieDan** [comment]
Everything related to the feed was implemented and tested. Closing issue #49
