### ISSUE TITLE
As a user, I want to post pictures

### ISSUE THREAD

**Issue by Bean-Green** [Polaroid-Soen-341/SOEN341#5]
### Story Points

-  I want to be able to post a picture through my own account.
-  I must be able to remove a picture that I posted on my account
-  I want to have a description that goes with my post.
-  The pictures that I post will be viewable by other people that follow me.
-  I want to post more than one picture in one post
-  My posts will be connect to my account

### Tasks

- [x] New post button on the frontend
- [x] Upload a photo
- [x] Store photo on backend database
- [x] Each post should be associated to one user

### Priority

High: must be done before sprint 3 deadline

**Comment by JackieDan** [comment]
Everything regarding creating posts have been implemented. Closing issue.

**Comment by Hamna-Akh** [comment]
<img width="714" alt="AT#4" src="https://user-images.githubusercontent.com/77466360/114638902-9abe6e00-9c9a-11eb-8819-fb1e1e04b687.png">
