### ISSUE TITLE
As a user I would like have a profile

### ISSUE THREAD

**Issue by NathanFortier** [Polaroid-Soen-341/SOEN341#53]
As a user I would like have a profile

- In my profile will display all previous posts.
- In my profile, I will have the option to create new posts
- My username is listed on my profile

- [x] display all posts in the profile
- [x] add create new post button and link to the backend
- [x] make it pretty

**Comment by Hamna-Akh** [comment]
Acceptance Test: Testing whether a user has a profile with accurate information present.
Priority: High
Steps:

Given: The user has logged in to Polaroid with a valid username and password. 
When: The user selects "My Profile"
Then: They will be redirected to their profile page 
And: Their profile page will contain information identifying them such as their username 
And: Their profile will contain any and all posts they have made in their current session or previous sessions

**Comment by Hamna-Akh** [comment]
<img width="574" alt="AT#3" src="https://user-images.githubusercontent.com/77466360/114638445-9e052a00-9c99-11eb-98a7-1bce3d43e348.png">
