### ISSUE TITLE
As a user, I want to comment under pictures

### ISSUE THREAD

**Issue by RMXCrossal** [Polaroid-Soen-341/SOEN341#7]
As a user, I want to comment under my pictures and others' pictures.

- I am able to comment through my own account. 
- I am able to delete a comment made previously.
- I can like comments.
- I can unlike a comment.

Tasks

- [x] Create a comment section for pictures. #
- [x] Create postComment function to send http request to the backend
- [x] Get all comments from the database for a specific post
- [x] Display all the comments for a post

**Comment by JackieDan** [comment]
Commenting under posts feature is completed. Closing issue!

**Comment by Hamna-Akh** [comment]
<img width="670" alt="AT#7" src="https://user-images.githubusercontent.com/77466360/114938435-1a6c4a00-9e0d-11eb-87a3-d4eed628076a.png">
